#!/bin/sh

DMENU='dmenu -i -l 4'
choice=$(echo "shutdown\nreboot\nsuspend\ncancel" | $DMENU)

case "$choice" in
     shutdown) poweroff ;;
     reboot) reboot ;;
     suspend) systemctl suspend ;;
     cancel) exit 0 ;;
esac
