#!/bin/sh

[ -f "$1" ] && cp "$1" ~/.local/share/backgrounds/current-wallpaper.png && notify-send -i "$HOME/.local/share/backgrounds/current-wallpaper.png" "Wallpaper changed."

xwallpaper --zoom ~/.local/share/backgrounds/current-wallpaper.png
